#!/usr/bin/env bash
# Display 'To infinity and beyond indefinitely'with a
# sleep 2 in between each iteration
# 'I am invincible!!' when receiving a SIGTERM signal

while true
do
	echo "To infinty and beyond"
	sleep 2
	trap 'echo "I am invincible"' SIGTERM
done